resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meshery
images:
- name: controller
  newName: docker.io/tanishq1604/meshery-operator
  newTag: v0.1.0
- name: meshery-operator
  newName: meshery-operator
  newTag: stable-latest
