namePrefix: meshery-
namespace: meshery
resources:
- role.yaml
- role_binding.yaml
- controller_role.yaml
- controller_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_viewer_role.yaml
# Auth proxy related resources have been removed as we're now using
# Controller-Runtime's built-in auth protection for metrics
